### ISSUE TITLE
Ignoring docs_dir in mkdocs.yml

### ISSUE THREAD

**Issue by bdellegrazie** [xvik/gradle-mkdocs-plugin#8]
plugin version: `2.1.0`

We have an odd directory layout:
```
./build.gradle
./docs/mkdocs.yml
./docs/src/*.md
./docs/src/*/*.md
```

docs are generated as part of the root project and `build.gradle` is configured as follows:
```groovy
mkdocs {
  sourcesDir = 'docs'
  strict = true
  // Disable multi-version support
  publish.docPath = null
  extras = [
    'version': "${-> project.version}"
  ]
}
```

`docs/mkdocs.yml` looks like:
```yaml
docs_dir: "src"
plugins:
  - search:
      separator: '[_\s\-\.]+'
      min_search_length: 3
      lang: ['en']
      prebuild_index: python
  - markdownextradata
... other elements elided
```

Now when running `mkdocsServe` or `mkdocsBuild` I get:
```
Execution failed for task ':mkdocsBuild'.
> Mkdocs documentation sources directory not found: docs/docs
```

This used to work on version `2.0.1` of the plugin and only appears when using the new `extras` capability of version `2.1.0`

Any suggestions?
Thanks
